const { test, expect } = require("@playwright/test");
test.use({ reducedMotion: "reduce" });

test("English persists and a visitor registers a correctly priced day package", async ({ page }, info) => {
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/");
  await page.getByRole("button", { name: "English", exact: true }).click();
  await expect(page.locator("html")).toHaveAttribute("lang", "en");
  await expect(page.getByRole("heading", { name: "Come to learn. Stay to create value." })).toBeVisible();
  await page.reload();
  await expect(page.getByRole("button", { name: "English", exact: true })).toHaveAttribute("aria-pressed", "true");
  await page.getByRole("button", { name: "Online registration", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Register your Wellness Farm visit" })).toBeVisible();
  const day = page.locator(".learning-package").filter({ hasText: "Day Package" });
  await expect(day).toContainText("450,000");
  await expect(page.locator(".learning-package").filter({ hasText: "Week Package" })).toContainText("2,000,000");
  await expect(page.locator(".learning-package").filter({ hasText: "Month Package" })).toContainText("9,000,000");
  await expect(page.getByRole("heading", { name: "Month Package", exact: true })).toBeVisible();
  await expect(page.locator(".online-registration table")).toHaveCount(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: `test-results/online-en-${info.project.name}.png`, fullPage: true });
  await day.getByRole("button", { name: "Register for this package" }).click();
  await page.locator("#auth-form").getByRole("button", { name: "Create account", exact: true }).click();
  await page.locator('#auth-form input[name="name"]').fill("Nguyễn Visitor");
  await page.locator('#auth-form input[name="email"]').fill(`visitor-${Date.now()}-${info.project.name}@example.test`);
  await page.locator('#auth-form input[name="password"]').fill("Visitor-test-12345");
  await expect(page.locator('#auth-form input')).toHaveCount(3);
  await page.locator('#auth-form button[type="submit"]').click();
  await expect(page.getByRole("heading", { name: "New · Visitor profiles" })).toBeVisible();
  await page.getByLabel("Full name", { exact: false }).fill("Nguyễn Guest");
  await page.getByLabel("Date of birth", { exact: false }).fill("1960-01-01");
  await page.locator('#record-form button[type="submit"]').click();
  await expect(page.getByRole("heading", { name: "New · Registrations & stays" })).toBeVisible();
  await expect(page.locator("#quote")).toContainText("450,000");
  await page.getByLabel("Number of package periods", { exact: false }).fill("2");
  await expect(page.locator("#quote")).toContainText("900,000");
  await page.locator('#record-form button[type="submit"]').click();
  await expect(page.getByRole("dialog")).not.toBeVisible();
  const bookings = await (await page.request.get("/api/bookings")).json();
  expect(bookings).toHaveLength(1);
  expect(bookings[0]).toMatchObject({ total: 900000, duration: 2, health_tier: "day", service_priority: 0, status: "Chờ duyệt" });
  expect(bookings[0].health_entitlements).toMatchObject({ workshops: true, talkshows: true, all_activities: true, expert_checkups: false });
  await expect(page.locator("#main")).toContainText("Day Package");
  await page.locator("#status-filter").selectOption({ label: "Pending review" });
  await expect(page.locator("#main tbody tr")).toHaveCount(1);
  await page.locator("#status-filter").selectOption({ label: "Confirmed" });
  await expect(page.locator("#main tbody tr")).toHaveCount(0);
  await page.locator("#status-filter").selectOption({ label: "All statuses" });
  await page.getByRole("button", { name: "Tiếng Việt", exact: true }).click();
  await expect(page.locator("html")).toHaveAttribute("lang", "vi");
  await expect(page.locator("#main")).toContainText("Nguyễn Guest");
  await expect(page.locator("#main")).toContainText("Gói Ngày");
  expect(errors).toEqual([]);
});

test("English public navigation translates empty states and full package benefits", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "English", exact: true }).click();
  await page.locator('nav [data-id="workshops"]').click();
  await expect(page.getByRole("heading", { name: "Workshop and talkshow schedule" })).toBeVisible();
  await page.getByRole("button", { name: "Crafts", exact: true }).first().click();
  await expect(page.getByRole("heading", { name: "No sessions for this topic yet" })).toBeVisible();
  await page.locator('nav [data-id="artisans"]').click();
  await expect(page.getByRole("heading", { name: "Silver Artisans and their creations" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Community impact" })).toBeVisible();
  await page.locator('nav [data-id="packages"]').click();
  const plans = page.locator(".learning-package");
  await expect(plans).toHaveCount(3);
  for (const plan of await plans.all()) {
    for (const benefit of ["Farm experiences", "Workshop participation", "Talkshow participation", "Blood pressure & heart rate screening", "Food & drinks"]) {
      await expect(plan.locator(".registration-plan-benefits")).toContainText(benefit);
    }
    await expect(plan.getByRole("button", { name: "Register for this package" })).toBeVisible();
  }
  const day = plans.filter({ hasText: "Day Package" });
  const week = plans.filter({ hasText: "Week Package" });
  const month = plans.filter({ hasText: "Month Package" });
  await expect(day).toContainText("Standard booking order");
  await expect(day).not.toContainText("Nutrition advice");
  await expect(week).toContainText("Health monitoring twice a day for 7 days");
  await expect(week).toContainText("Nutrition advice");
  await expect(week).not.toContainText("Regular expert check-ups");
  await expect(month).toContainText("Regular expert check-ups");
  await expect(month).toContainText("Weekly nutrition advice");
  await expect(month).toContainText("Highest priority for case processing");
  await expect(page.locator(".online-registration table")).toHaveCount(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole("button", { name: "Tiếng Việt", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Đăng ký online tại Wellness Farm" })).toBeVisible();
});
